# Generated by Django 2.0.5 on 2018-05-14 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='address',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='creator',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='remark',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='useremail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户Email'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='usertitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='createtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='创建人'),
        ),
    ]
