# Generated by Django 2.0.5 on 2018-05-15 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mailmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='creator',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
