# Generated by Django 2.0.7 on 2018-10-09 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180515_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(verbose_name='信息表序列号')),
                ('title', models.CharField(max_length=500, verbose_name='项目描述')),
                ('createtime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='enddate',
            field=models.DateTimeField(verbose_name='项目结束日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.CharField(max_length=4000, verbose_name='提醒内容'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='sendtime',
            field=models.DateTimeField(verbose_name='提醒日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='startdate',
            field=models.DateTimeField(verbose_name='项目开始日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='title',
            field=models.CharField(max_length=500, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='type',
            field=models.CharField(default=11, max_length=500, verbose_name='类别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='usertitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='负责人'),
        ),
    ]
