# Generated by Django 2.0.7 on 2018-10-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181009_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='title',
            field=models.CharField(choices=[('', '--请选择--'), ('联动价格更新', '联动价格更新'), ('合同到期', '合同到期'), ('返利到期追踪', '返利到期追踪'), ('设备分期付款', '设备分期付款'), ('国产化进度更新', '国产化进度更新'), ('日常项目更新', '日常项目更新')], max_length=500, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='type',
            field=models.CharField(choices=[('', '--请选择--'), ('联动价格更新', '联动价格更新'), ('合同到期', '合同到期'), ('返利到期追踪', '返利到期追踪'), ('设备分期付款', '设备分期付款'), ('国产化进度更新', '国产化进度更新'), ('日常项目更新', '日常项目更新')], max_length=500, verbose_name='类别'),
        ),
    ]
