# Generated by Django 2.0.7 on 2018-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181011_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='enddate',
            field=models.DateField(verbose_name='项目结束日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='sendtime',
            field=models.DateField(verbose_name='提醒日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='startdate',
            field=models.DateField(verbose_name='项目开始日期'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='title',
            field=models.CharField(max_length=500, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='usertitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='负责人名称'),
        ),
    ]
