# Generated by Django 2.0.7 on 2018-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181015_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='title',
        ),
        migrations.AddField(
            model_name='maillog',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='结果'),
        ),
    ]
